version: "2"
services:

  fluent-collector:
    container_name: fluent-collector
    image:  fluent-collector-efk
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/logs
    ports:
      - "8888:8888"